name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: '版本标签 (例如: v1.0.0)'
        required: false
        type: string
        default: ''

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到 GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置版本标签
        id: version
        run: |
          if [ -n "${{ inputs.version_tag }}" ]; then
            echo "version=${{ inputs.version_tag }}" >> $GITHUB_OUTPUT
            echo "has_custom_version=true" >> $GITHUB_OUTPUT
          else
            echo "version=" >> $GITHUB_OUTPUT
            echo "has_custom_version=false" >> $GITHUB_OUTPUT
          fi

      - name: 提取 Docker 元数据 (手动版本)
        if: steps.version.outputs.has_custom_version == 'true'
        id: meta-custom
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
          flavor: |
            latest=false

      - name: 提取 Docker 元数据 (自动版本)
        if: steps.version.outputs.has_custom_version == 'false'
        id: meta-auto
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
          flavor: |
            latest=false

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-custom.outputs.tags || steps.meta-auto.outputs.tags }}
          labels: ${{ steps.meta-custom.outputs.labels || steps.meta-auto.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 输出镜像信息
        run: |
          echo "### 🐳 Docker镜像构建成功！" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**镜像标签：**" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta-custom.outputs.tags || steps.meta-auto.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.version.outputs.has_custom_version }}" == "true" ]; then
            echo "**手动版本标签：** ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          fi

